### ISSUE TITLE
Does not work with Arduino 1.0.1 IDE

### ISSUE THREAD

**Issue by GoogleCodeExporter** [cniweb/avr-netino#4]
```
What steps will reproduce the problem?
1. Download Arduino 1.0.1
2. Extract avr-netino-10May2011.zip and avr-netino-19Jan2012.zip into Arduino 
install dir and overwrite existing files
3. Start Arduino IDE, select Tools-Board-AvrNetIO644 (or another AvrNetIO 
board).
4. Open an example, ie File-Examples-AvrNetino-ANIO_LCD
5. Start a verify, click Verify

A lot of compile errors:

In file included from 
D:\AVR-Net-IO\avrnetino\arduino-1.0.1-windows\arduino-1.0.1\hardware\avrnetio\co
res\avrnetio/Arduino.h:212,
                 from ANIO_LCD.cpp:4:
D:\AVR-Net-IO\avrnetino\arduino-1.0.1-windows\arduino-1.0.1\hardware\avrnetio\co
res\avrnetio/pins_arduino.h:53: error: expected identifier before numeric 
constant
D:\AVR-Net-IO\avrnetino\arduino-1.0.1-windows\arduino-1.0.1\hardware\avrnetio\co
res\avrnetio/pins_arduino.h:53: error: expected `}' before numeric constant
D:\AVR-Net-IO\avrnetino\arduino-1.0.1-windows\arduino-1.0.1\hardware\avrnetio\co
res\avrnetio/pins_arduino.h:53: error: expected unqualified-id before numeric 
constant
D:\AVR-Net-IO\avrnetino\arduino-1.0.1-windows\arduino-1.0.1\hardware\avrnetio\co
res\avrnetio/pins_arduino.h:114: error: expected identifier before numeric 
constant
D:\AVR-Net-IO\avrnetino\arduino-1.0.1-windows\arduino-1.0.1\hardware\avrnetio\co
res\avrnetio/pins_arduino.h:114: error: expected `}' before numeric constant
D:\AVR-Net-IO\avrnetino\arduino-1.0.1-windows\arduino-1.0.1\hardware\avrnetio\co
res\avrnetio/pins_arduino.h:114: error: expected unqualified-id before numeric 
constant
D:\AVR-Net-IO\avrnetino\arduino-1.0.1-windows\arduino-1.0.1\hardware\avrnetio\co
res\avrnetio/pins_arduino.h:132: error: expected declaration before '}' token

On what operating system?
Tested on Windows 7 (x64)


```

Original issue reported on code.google.com by `hjg...@gmail.com` on 7 Sep 2012 at 12:19
